apiVersion: v1
kind: Pod
metadata:
  name: nginx-user5
  labels:
    app: nginx-user5
spec:
  containers:
    - name: nginx-user5
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /var/log/nginx
          name: share-logs
        - mountPath: /etc/nginx/
          name: nginx-conf
          readOnly: true
    - name: fluentd
      image: fluentd:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /logs
          name: share-logs
        - mountPath: /fluentd/etc
          name: fluent-conf
          readOnly: true
  volumes:
    - name: share-logs
      emptyDir: {}
    - configMap:
        items:
          - key: nginx.conf 
            path: nginx.conf 
        name: nginx-conf
      name: nginx-conf
    - configMap:
        items:
          - key: fluent.conf
            path: fluent.conf
        name: fluent-conf
      name: fluent-conf