apiVersion: v1
kind: Pod
metadata:
  name: wordpress-user5
  labels:
    version: "1"
    app: wordpress-user5
spec:
  containers:
    - name: wordpress-user5
      image: wordpress:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: MYSQL_DATABASE
              name: mysql-secret-user5
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mysql-secret-user5
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mysql-secret-user5
